backup-live/config/routes.rb
Rails.application.routes.draw do
  # root :to => 'https://www.facebook.com/goxskin'
  root :to => redirect("https://www.facebook.com/goxskin")
  #'page#home'
  devise_for :users, :controllers => { :omniauth_callbacks => "callbacks" }
  get 'store', to: "page#store"
  get 'apple_watch', to: "page#apple_watch"
  get 'iphone6', to: "page#iphone6"
  get 'make', to: "page#make"
  get '/admin', to: "admin#login"

end

backup-live/app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable,:omniauthable,:omniauth_providers=>[:facebook,:instagram]
    def self.from_omniauth(auth)
      where(provider: auth.provider, uid: auth.uid).first_or_create do |user|
        user.provider = auth.provider
        user.uid = auth.uid
        user.email = auth.info.email
        user.password = Devise.friendly_token[0,20]
      end
  end
end

backup-live/app/controllers/admin_controller.rb
class AdminController < ApplicationController
	before_filter :authenticate_user!
	before_action :require_admin
	def login
		
	end




  private
  def require_admin
   if !current_user.try(:admin?)
      flash[:error] = "You must be logged as admin to access this section"
      redirect_to root_path # halts request cycle
    end
  end
end

backup-live/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

backup-live/app/controllers/callbacks_controller.rb
class CallbacksController < Devise::OmniauthCallbacksController
    def facebook
    	auth=request.env["omniauth.auth"]
    	email=auth["info"].email
    	
    # You need to implement the method below in your model (e.g. app/models/user.rb)
    @user = User.where(:email=>email).first
    # render :plain => @user.inspect
    if @user
      sign_in_and_redirect @user, :event => :authentication #this will throw if @user is not activated
      set_flash_message(:notice, :success, :kind => "Facebook") if is_navigational_format?
    else
    	user = User.create(name:auth.extra.raw_info.name,
                         provider:auth.provider,
                         uid:auth.uid,
                         email:auth.info.email,
                         password:Devise.friendly_token[0,20]
                         )

      sign_in_and_redirect user
    end
    end
    def instagram
    	render :plain => request.env["omniauth.auth"].to_json

        # @user = User.from_omniauth(request.env["omniauth.auth"])
        # sign_in_and_redirect @user
    end
end

backup-live/app/controllers/page_controller.rb
class PageController < ApplicationController
	def home

	end
	def store
		
	end
	def apple_watch
		
	end
	def iphone6
		
	end
	def make

	end
end

backup-live/app/helpers/admin_helper.rb
module AdminHelper
end

backup-live/app/helpers/application_helper.rb
module ApplicationHelper
  def active_class?(*paths)
    active = false
    paths.each { |path| active ||= current_page?(path) }
    active ? 'xskin-active' : nil
  end
end

backup-live/app/helpers/page_helper.rb
module PageHelper
end

backup-live/app/views/admin/login.html.erb
<section classs="admin-login">
  <div class="row">
	  <h3 class="text-center">Welcome To Admin</h3>
	</div>
	<div class="row custom-login">
		<%= form_for(:user, :url => session_path(:user),:remote=>true) do |f| %>
            <div class="field">
              <%= f.email_field :email, autofocus: true %>
            </div>
            <div class="field">
              <%= f.password_field :password, autocomplete: "off" %>
            </div>
            <div class="field sign-in-forget-pass">
              
   					<%= f.submit "Login",:class=>"button" %> 
</div>
<% end %>
	</div>
</section>

backup-live/app/views/layouts/_footer.html.erb
<footer>
      <div class="row">

      <div class="small-12 show-for-small-only left medium-4">
          <div class="play-store">
            <a href="#"><%=image_tag"app-store.png" %></a>
            <a href="#"><%=image_tag"google-play-store.png" %></a>
          </div>

          <div class="social-icon">
            <ul>
              <li><a href="#"><i class="fa fa-facebook"></i></a></li>
              <li><a href="#"><i class="fa fa-weibo"></i></a></li>
              <li><a href="#"><i class="fa fa-twitter"></i></a></li>
              <li><a href="#"><i class="fa fa-instagram"></i></a></li>
              <li><a href="#"><i class="fa fa-youtube-play"></i></a></li>
              <li><a href="#"><i class="fa fa-weixin"></i></a></li>
              <li><a href="#"><%=image_tag"vimeo.png" %></a></li>
              <li><a href="#"><i class="fa fa-google-plus"></i></a></li>
            </ul>
          </div>
          <!-- Social icon close from here -->

          <div class="newsletter">
            <form>
            
            
            <div class="field">
            <label>newsletter</label>
              <input type="text" placeholder="" />
              </div>
              <div class="submit">
                <input type="submit" class="smooth" value="submit" />
              </div>
            </form>
          </div>

        </div>
        <!-- app store close from here -->


        <div class="large-3 small-6 left medium-4">
          <h4>products</h4>
          <ul class="xskin-footer-links">
            <li><a href="#">gift card</a></li>
            <li><a href="#">iphone 6 case</a></li>
            <li><a href="#">iphone 5 case</a></li>
            <li><a href="#">iphone 4 case</a></li>
            <li><a href="#">galaxy s5 case</a></li>
            <li><a href="#">galaxy s4 case</a></li>
            <li><a href="#">galaxy s3 case</a></li>
            <li><a href="#">ipad 3/4 case</a></li>
            <li><a href="#">all products</a></li>
          </ul>
        </div>
        <div class="large-3 small-6 left medium-4">
          <h4>support</h4>
          <ul class="xskin-footer-links">
            <li><a href="#">faq</a></li>
            <li><a href="#">subscription</a></li>
            <li><a href="#">privacy policy</a></li>
            <li><a href="#">term and conditions</a></li>
            <li><a href="#">affiliate</a></li>
            <li><a href="#">testimonial</a></li>
            <li><a href="#">developer</a></li>
            <li><a href="#">careers</a></li>
            <li><a href="#">spotting</a></li>
          </ul>
        </div>
        <div class="large-6 left medium-4 hide-for-small-only">
          <div class="play-store">
            <a href="#"><%=image_tag"app-store.png" %></a>
            <a href="#"><%=image_tag"google-play-store.png"%></a>
          </div>

          <div class="social-icon">
            <ul>
              <li><a href="#"><i class="fa fa-facebook"></i></a></li>
              <li><a href="#"><i class="fa fa-weibo"></i></a></li>
              <li><a href="#"><i class="fa fa-twitter"></i></a></li>
              <li><a href="#"><i class="fa fa-instagram"></i></a></li>
              <li><a href="#"><i class="fa fa-youtube-play"></i></a></li>
              <li><a href="#"><i class="fa fa-weixin"></i></a></li>
              <li><a href="#"><%=image_tag"vimeo.png"%></a></li>
              <li><a href="#"><i class="fa fa-google-plus"></i></a></li>
            </ul>
          </div>
          <!-- Social icon close from here -->

          <div class="newsletter">
            <form>
            
            
            <div class="field">
            <label>newsletter</label>
              <input type="text" placeholder="" />
              </div>
              <div class="submit">
                <input type="submit" class="smooth" value="submit" />
              </div>
            </form>
          </div>

        </div>
        <!-- app store close from here -->
      </div>
    </footer>

backup-live/app/views/layouts/_header.html.erb
<header>
        <div class="row">
        <div class="xskin-login text-right">
          <ul class="xskin-login-language">
            <li class="hide-for-small-only"><a href="#">ENGLISH <sup>.</sup></a></li>
      <% if user_signed_in? %>
            <li class="login last">
            <%=link_to"Logout",destroy_user_session_path,:method=>"delete"  %>
            </li>
            <li class="login last">
            <%=link_to"Cart","javascript:void(0);"  %>
            </li>
      <% else %>      
          <li class="login last">
          <%=link_to"LOGIN",new_user_session_path, :title=>"Login to start"  %>
          </li>
      <% end %>            
          </ul>
        </div>

        <div class="xskin-menu-with-logo">
            <div class="large-4 medium-4 columns">
            <div class="xskin-logo">
            <%= link_to image_tag('Xskin-logo.png'), root_path,:class =>"logo left",:alt=>"Skin" ,:title=>"XSkin"  %>
             
              </div>
              <div class="show-for-small-only mobile-search">
                <input type="submit" value="Send" />
              </div>
            </div>
            <!-- Xskin-logo close from here -->

            <!-- Search area for only mobile -->
            <div class="show-for-small-only xskin-mobile-search">
                <div class="enter-keywords" style="display: none;">
                <input type="text" placeholder="Search Here |" />
                </div>
                <div class="press-enter mobile-search" style="display: none;">
                  <input type="submit" value="Send" />
                </div>
              </div>
          <div class="large-8 medium-8 columns hide-for-small-only">
            <ul class="xskin-menu">
              <li><%= link_to"MAKE YOUR CASE",make_path,:class => active_class?(make_path) %></li>
              <li><%= link_to"STORE",store_path,:class => active_class?(store_path) %></li>
              <li><%= link_to"iPHONE6",iphone6_path,:class => active_class?(iphone6_path) %></li>
              <li><%= link_to"APPLE WATCH",apple_watch_path,:class => active_class?(apple_watch_path) %></li>
              <li class="xskin-search"><input type="submit" value="Send" /></li>
                </ul>
                </div>
                <!-- Xskin menu for destop close from here -->
                

                <nav class="tab-bar show-for-small-only">
                  <section class="left-small">
                    <a href="#" class="left-off-canvas-toggle menu-icon" aria-expanded="false"><span></span></a>
                    </section>
                      <section class="right tab-bar-section">
                        <h1 class="title">Menu</h1>
                      </section>
                      </nav>

                         </div>
                        <aside class="left-off-canvas-menu">
                          <ul class="off-canvas-list">
                            <li><label>Menu</label></li>
                            <li><a href="make-your-case.html">MAKE YOUR CASE</a></li>
                            <li><a href="#">STORE</a></li>
                            <li><a href="#">iPHONE6</a></li>
                            <li><a href="#">APPLE WATCH</a></li>
                          </ul>
                        </aside>
                        </div>
                      <!-- row close from here -->
                        </header>

backup-live/app/views/layouts/_messages.html.erb
<%# Rails flash messages styled for Zurb Foundation %>
<% flash.each do |name, msg| %>
  <% if msg.is_a?(String) %>
  
    <div data-alert class="row xskin-flash-message text-center alert-box radius <%= name.to_s == 'notice' ? 'success' : 'alert' %>">
      <%= content_tag :div, msg %>
      <a href="#" class="close">&times;</a>
    </div>
  <% end %>
<% end %>

backup-live/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <meta name="description" content="Skin - Case with your Instagram, Facebook and personal photos, and we use our patent pending technology to turn it into a real iPhone 6S/6/5S/5C/5 / iPhone 4S/4 / iPad 4/3/2 / iPod Touch 5/4 / Samsung Galaxy S4/III/II case.">
    <meta name="author" content="Skin">
    <meta name="copyright" content="Skin, Copyright (c) 2015">
    <title><%= content_for?(:title) ? yield(:title) : "xSkiN" %></title>
 <link href='https://fonts.googleapis.com/css?family=Open+Sans:400,300italic,300,400italic,600,600italic,700,700italic,800' rel='stylesheet' type='text/css'>
    <link href='https://fonts.googleapis.com/css?family=Open+Sans+Condensed:300,300italic,700' rel='stylesheet' type='text/css'>
    <link rel="icon" href="<%= ActionController::Base.helpers.asset_path('favicon.png') %>" type="image/png" sizes="16x16"> 

    <%= stylesheet_link_tag    "application" %>
       <%= csrf_meta_tags %>
  </head>

  <body class="<%=controller.controller_name%>_<%= controller.action_name%>">
  <div data-offcanvas="" class="off-canvas-wrap docs-wrap">
        <div class="inner-wrap">
        <% if (controller.controller_name=='sessions' && controller.action_name=="new") || (controller.controller_name=='registrations' && controller.action_name=="new") %>
        <% else %>
          <%= render 'layouts/header'  %>
        <% end %>
        <%= render 'layouts/messages' %>  



    <%= yield %>
    <a href="#" class="exit-off-canvas"></a>
    </div>
    </div>
 <%= javascript_include_tag "vendor/modernizr" %>
    <%= javascript_include_tag "application", 'data-turbolinks-track' => true %>
<%= render 'layouts/footer'  %>
  </body>
</html>

backup-live/app/views/page/home.html.erb
<section class="skin-content">
    <div class="row">
      <div class="xskin-content-section">

      <!-- sidebar start from here -->
        <div class="medium-3 left hide-for-small-only">
          <div class="sidebar">
            <div class="iphone-6">
            <%= image_tag "iPhone6-front.jpg" %>              
              <div class="masking smooth">
                <div class="xskin-add-to-cart">
                  <div class="add-to-cart">
                  <a href="#"><span class="smooth cart">
                  <%= image_tag "zoom.png" %>
                    </span></a>
                    <a href="#"><span class="smooth cart your-cart">
                    <%= image_tag "add-to-cart.png" %>
                    </span></a>
                  </div>
                </div>
              </div>
            </div>
            <!-- iPhone6 close from here -->

            <div class="iphone-6">
            <%= image_tag "iPhone6-back.jpg" %>
              <div class="masking smooth">
                <div class="xskin-add-to-cart">
                  <div class="add-to-cart">
                  <a href="#"><span class="smooth cart">
                    <%= image_tag "zoom.png" %>
                    </span></a>
                    <a href="#"><span class="smooth cart your-cart">
                    <%= image_tag "add-to-cart.png" %>
                    </span></a>
                  </div>
                </div>
              </div>
            </div>
            <!-- iPhone6 close from here -->
          </div>
        </div>
        <!-- sidebar close from here -->


        <!-- slider start from here -->
        <div class="medium-6 columns hide-for-small-only">
          <div class="xskin-slider">
            <div class="xskin-slide">
              <%=image_tag"iphone-background.jpg" %>
            </div>

            <div class="xskin-slide-caption">
              <div class="caption">
                <div class="make-your-own-skin">
                  <div class="slide-cap">
                    <h2>make your own</h2>
                    <h1>skin</h1>
                    <a href="#" class="button">Learn More</a>
                  </div>
                </div>
              </div>
            </div>
            <!-- slide caption close from here -->
          </div>
        </div>
        <!-- slider close from here -->


        <div class="medium-3 left hide-for-small-only">
          <div class="sidebar">
            <div class="iphone-6">
              <%=image_tag"girl-using-iphone.jpg" %>
              <div class="xskin-top-design">
              <div class="caption">
                <div class="make-your-own-skin">
                  <div class="slide-cap">
                    <h3>top 100<br><span>Design</span></h3>
                    <a href="#" class="button">see more</a>
                  </div>
                </div>
              </div>
              </div>
              <!-- top design caption close from here -->

            </div>
            <div class="iphone-6">
              <%=image_tag"mans-using-iphone.jpg" %>
              <div class="xskin-top-design">
              <div class="caption">
                <div class="make-your-own-skin">
                  <div class="slide-cap">
                  <h5>Give your friend</h5>
                    <h3>get &dollar;10</h3>
                    <a href="#" class="button">see more</a>
                  </div>
                </div>
              </div>
              </div>
              <!-- top design caption close from here -->
            </div>
          </div>
        </div>
        </div>

      <!-- design only for mobile -->
      <div class="small-12 show-for-small-only">
          <div class="xskin-slider">
            <div class="xskin-slide">
              <%=image_tag "iphone-background.jpg" %>
            </div>

            <div class="xskin-slide-caption">
              <div class="caption">
                <div class="make-your-own-skin">
                  <div class="slide-cap">
                    <h2>make your own</h2>
                    <h1>skin</h1>
                    <a class="button" href="#">Learn More</a>
                  </div>
                </div>
              </div>
            </div>
            <!-- slide caption close from here -->
          </div>
        </div>


        <div class="small-12 left show-for-small-only">
          <div class="sidebar">
            <div class="iphone-6">
              <%=image_tag"girl-using-iphone.jpg" %>
              <div class="xskin-top-design">
              <div class="caption">
                <div class="make-your-own-skin">
                  <div class="slide-cap">
                    <h3>top 100<br><span>Design</span></h3>
                    <a href="#" class="button">see more</a>
                  </div>
                </div>
              </div>
              </div>
              <!-- top design caption close from here -->

            </div>
            <div class="iphone-6">
              <%=image_tag"mans-using-iphone.jpg" %>

              <div class="xskin-top-design">
              <div class="caption">
                <div class="make-your-own-skin">
                  <div class="slide-cap">
                  <h5>Give your friend</h5>
                    <h3>get &dollar;10</h3>
                    <a href="#" class="button">see more</a>
                  </div>
                </div>
              </div>
              </div>
              <!-- top design caption close from here -->
            </div>
          </div>
        </div>


        <div class="small-12 left show-for-small-only">
          <div class="sidebar">
            <div class="iphone-6 mobile-view">
              <%=image_tag"iPhone6-front.jpg" %>
              <div class="masking smooth">
                <div class="xskin-add-to-cart">
                  <div class="add-to-cart">
                  <a href="#"><span class="smooth cart">
                    <%=image_tag"zoom.png" %>
                    </span></a>
                    <a href="#"><span class="smooth cart your-cart">
                    <%=image_tag"add-to-cart.png" %>
                    </span></a>
                  </div>
                </div>
              </div>
            </div>
            <!-- iPhone6 close from here -->

            <div class="iphone-6 mobile-view">
              <%=image_tag"iPhone6-back.jpg" %>
              <div class="masking smooth">
                <div class="xskin-add-to-cart">
                  <div class="add-to-cart">
                  <a href="#"><span class="smooth cart">
                    <%=image_tag "zoom.png" %>
                    </span></a>
                    <a href="#"><span class="smooth cart your-cart">
                    <%=image_tag"add-to-cart.png" %>
                    </span></a>
                  </div>
                </div>
              </div>
            </div>
            <!-- iPhone6 close from here -->
          </div>
        </div>

        </div>

      </section>