config/routes.rb
Rails.application.routes.draw do
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  # root 'page#home'
  get 'page/home'
  devise_for :users, :controllers => { :omniauth_callbacks => "callbacks" }
  get 'store', to: "page#store"
  get 'apple_watch', to: "page#apple_watch"
  get 'iphone6', to: "page#iphone6"
  get 'make', to: "page#make"
  # get '/admin', to: "admin#login"
  get 'gallery', to: "page#gallery" 
  get 'invite', to: "page#invite" 
  get 'track', to: "page#track" 
  get 'promotion', to: "page#promotion" 
  get 'top_design', to: "page#top_design" 
  get 'demo',to: 'page#demo'
  get 'terms',to: 'page#terms'
  get 'developer',to: 'page#developer'
  get 'careers',to: 'page#careers'
  get 'faq',to: 'page#faq'
  get 'privacy',to: 'page#privacy'
  get 'terms',to: 'page#terms'
  get 'contact',to: 'page#contact'
  get 'testimonial',to: 'page#testimonial'
  get 'affiliate',to: 'page#affiliate'
  get 'spotting',to: 'page#spotting'
  post "page/select_currency" 
  post "shipping/address_edit" 
  root :to => redirect("https://www.facebook.com/goxskin")

end

app/models/country.rb
class Country < ActiveRecord::Base
end

app/models/currency.rb
class Currency < ActiveRecord::Base
end

app/models/home_slider.rb
class HomeSlider < ActiveRecord::Base
  mount_uploader :image, HomeSliderUploader
end

app/models/newsletter.rb
class Newsletter < ActiveRecord::Base
	validates :email, presence: true, uniqueness: true
end

app/models/shipping_address.rb
class ShippingAddress < ActiveRecord::Base
  belongs_to :user
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  belongs_to :currency
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable,:omniauthable,:omniauth_providers=>[:facebook,:instagram]
    def self.from_omniauth(auth)
      where(provider: auth.provider, uid: auth.uid).first_or_create do |user|
        user.provider = auth.provider
        user.uid = auth.uid
        user.email = auth.info.email
        user.password = Devise.friendly_token[0,20]
      end
  end
end

app/models/user_metum.rb
class UserMetum < ActiveRecord::Base
  belongs_to :user
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  private

  # Overwriting the sign_out redirect path method
  def after_sign_out_path_for(resource_or_scope)
    # root_path
    demo_path
  end
  def after_sign_in_path_for(resource)
  	demo_path
  	end
end

app/controllers/callbacks_controller.rb
class CallbacksController < Devise::OmniauthCallbacksController
    def facebook
    	auth=request.env["omniauth.auth"]
    	email=auth["info"].email
    	
    # You need to implement the method below in your model (e.g. app/models/user.rb)
    @user = User.where(:email=>email).first
    # render :plain => @user.inspect
    if @user
      sign_in_and_redirect @user, :event => :authentication #this will throw if @user is not activated
      set_flash_message(:notice, :success, :kind => "Facebook") if is_navigational_format?
    else
    	user = User.create(name:auth.extra.raw_info.name,
                         provider:auth.provider,
                         uid:auth.uid,
                         email:auth.info.email,
                         password:Devise.friendly_token[0,20]
                         )

      sign_in_and_redirect user
    end
    end
    def instagram
    	render :plain => request.env["omniauth.auth"].to_json

        # @user = User.from_omniauth(request.env["omniauth.auth"])
        # sign_in_and_redirect @user
    end
end

app/controllers/page_controller.rb
class PageController < ApplicationController
	before_action :authenticate_user!, :except => [:home,:store,:apple_watch,:iphone6,:make,:top_design,:demo,:faq,:privacy,:developer,:terms,:testimonial,:contact,:spotting,:careers]
	def home

	end
	def demo
	  @arrHomeSliders = HomeSlider.all
	end

	def store
		
	end
	def apple_watch
		
	end
	def iphone6
		
	end
	def make

	end
	def gallery
		
	end
	def invite
		
	end
	def promotion
		
	end
	def top_design
		
	end
	def testimonial
		
	end
	def affiliate
		
	end
	def select_currency
		if params[:selected_currency]
			cookies[:currency] = {
				   :value => params[:selected_currency],
				   :expires => 1.year.from_now
				 }
			flash[:success]="Sucessfully selected the currency.";
			redirect_to request.referrer
		else
			flash[:error]="Please select currency";
			redirect_to request.referrer
		end
	end
	def privacy
		
	end
	def developer
		
	end
	def careers
		
	end
	def terms

	end
	def faq
		
	end
	def contact
		
	end
	def spotting
		
	end
end

app/controllers/shipping_controller.rb
class ShippingController < ApplicationController
	def address_edit
		
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def active_class?(*paths)
    active = false
    paths.each { |path| active ||= current_page?(path) }
    active ? 'xskin-active' : nil
  end
end

app/helpers/page_helper.rb
module PageHelper
end

app/helpers/shipping_helper.rb
module ShippingHelper
end

app/views/layouts/_currency.html.erb
<% @arrCurrency = Currency.all %>
<div id="xskin-currencyModal" class="reveal-modal large" data-reveal aria-labelledby="videoModalTitle" aria-hidden="true" role="dialog">
  <h5>Choose your Currency</h5>
    <ul class="world-currency">

      <% if @arrCurrency.any? %>
        <% @arrCurrency.each do |arrCurrency| %>
          <% if arrCurrency.name == cookies[:currency] %>
            <li><a href="javascript:void(0);" class="active-currency"><%= arrCurrency.name %></a></li>

          <% else %>
            <li><a href="javascript:void(0);"><%= arrCurrency.name %></a></li>
            
          <% end %>
        <% end %>
      <% end %>
    </ul>
    <div class="clearfix"></div>
    <div class="confirm">
      <%=form_tag"/page/select_currency" do %>
      <%= hidden_field_tag"selected_currency" %>
      <%= submit_tag"Confirm" %>
      <% end %>
      

    </div>

        <a class="close-reveal-modal" aria-label="Close">&#215;</a>
      </div>
      <!-- Reveal Modals end -->

app/views/layouts/_footer.html.erb
<footer>
      <div class="row">

      <div class="small-12 show-for-small-only left medium-4">
          <div class="play-store">
            <a href="#"><%=image_tag"app-store.png" %></a>
            <a href="#"><%=image_tag"google-play-store.png" %></a>
          </div>

          <div class="social-icon">
            <ul>
              <li><a href="#"><i class="fa fa-facebook"></i></a></li>
              <li><a href="#"><i class="fa fa-weibo"></i></a></li>
              <li><a href="#"><i class="fa fa-twitter"></i></a></li>
              <li><a href="#"><i class="fa fa-instagram"></i></a></li>
              <li><a href="#"><i class="fa fa-youtube-play"></i></a></li>
              <li><a href="#"><i class="fa fa-weixin"></i></a></li>
              <li><a href="#"><%=image_tag"vimeo.png" %></a></li>
              <li><a href="#"><i class="fa fa-google-plus"></i></a></li>
            </ul>
          </div>
          <!-- Social icon close from here -->

          <div class="newsletter">
            <form>
            
            
            <div class="field">
            <label>newsletter</label>
              <input type="text" placeholder="" />
              </div>
              <div class="submit">
                <input type="submit" class="smooth" value="submit" />
              </div>
            </form>
          </div>

        </div>
        <!-- app store close from here -->


        <div class="large-3 small-6 left medium-4">
          <h4>products</h4>
          <ul class="xskin-footer-links">
            <li><a href="#">gift card</a></li>
            <li><a href="#">iphone 6 case</a></li>
            <li><a href="#">iphone 5 case</a></li>
            <li><a href="#">iphone 4 case</a></li>
            <li><a href="#">galaxy s5 case</a></li>
            <li><a href="#">galaxy s4 case</a></li>
            <li><a href="#">galaxy s3 case</a></li>
            <li><a href="#">ipad 3/4 case</a></li>
            <li><a href="#">all products</a></li>
          </ul>
        </div>
        <div class="large-3 small-6 left medium-4">
          <h4>support</h4>
          <ul class="xskin-footer-links">
            <li><%=link_to"Faq",faq_path %></li>
            <li><a href="#">subscription</a></li>
            <li><%=link_to"privacy policy",privacy_path%></li>
            <li><%=link_to"term and conditions", terms_path%></li>
            <li><%= link_to"affiliate",affiliate_path %></li>
            <li><%= link_to"testimonial",testimonial_path %></li>
            <li><%= link_to"developer",developer_path %></li>
            <li><%= link_to"careers",careers_path %></li>
            <li><%= link_to"spotting",spotting_path %></li>
          </ul>
        </div>
        <div class="large-6 left medium-4 hide-for-small-only">
          <div class="play-store">
            <a href="#"><%=image_tag"app-store.png" %></a>
            <a href="#"><%=image_tag"google-play-store.png"%></a>
          </div>

          <div class="social-icon">
            <ul>
              <li><a href="#"><i class="fa fa-facebook"></i></a></li>
              <li><a href="#"><i class="fa fa-weibo"></i></a></li>
              <li><a href="#"><i class="fa fa-twitter"></i></a></li>
              <li><a href="#"><i class="fa fa-instagram"></i></a></li>
              <li><a href="#"><i class="fa fa-youtube-play"></i></a></li>
              <li><a href="#"><i class="fa fa-weixin"></i></a></li>
              <li><a href="#"><%=image_tag"vimeo.png"%></a></li>
              <li><a href="#"><i class="fa fa-google-plus"></i></a></li>
            </ul>
          </div>
          <!-- Social icon close from here -->

          <div class="newsletter">
            <form>
            
            
            <div class="field">
            <label>newsletter</label>
              <input type="text" placeholder="" />
              </div>
              <div class="submit">
                <input type="submit" class="smooth" value="submit" />
              </div>
            </form>
          </div>

        </div>
        <!-- app store close from here -->
      </div>
    </footer>

app/views/layouts/_header.html.erb
<header>
    <div class="row">
      <div class="xskin-login text-right">
        <ul class="xskin-login-language">
          <li class="hide-for-small-only"><a data-reveal-id="xskin-currencyModal" href="#"><i class="fa fa-briefcase"></i>
          <% if cookies[:currency] %>
            <%= cookies[:currency] %>
          <% else %>
          CAD ($)
          <% end %>
          </a></li>
      <% if user_signed_in? %>
      <li class="login last">
            <%=link_to"MyAccount",edit_user_registration_path %>
            </li>
            <li class="login last">
            <%=link_to"Logout",destroy_user_session_path,:method=>"delete"  %>
            </li>
            <li class="login last">
            <%=link_to"Cart","javascript:void(0);"  %>
            </li>
      <% else %>      
          <li class="login last">
          <%=link_to"LOGIN",new_user_session_path, :title=>"Login to start"  %>
          </li>
      <% end %>            
          </ul>
        </div>

        <div class="xskin-menu-with-logo">
            <div class="large-4 medium-4 columns">
            <div class="xskin-logo">
            <%= link_to image_tag('Xskin-logo.png'), demo_path,:class =>"logo left",:alt=>"Skin" ,:title=>"XSkin"  %>
             
              </div>
              <div class="show-for-small-only mobile-search">
                <input type="submit" value="Send" />
              </div>
            </div>
            <!-- Xskin-logo close from here -->

            <!-- Search area for only mobile -->
           
          <div class="large-8 medium-8 columns hide-for-small-only">
            <ul class="xskin-menu">
              <li><%= link_to"MAKE YOUR CASE",make_path,:class => active_class?(make_path) %></li>
              <li><%= link_to"STORE",store_path,:class => active_class?(store_path) %>
                <ul class="sub-menu smooth">
                      <li>
                        <ul class="xskin-submenu">
                        <span class="menu-title">COLLECTION</span>
                          <li><a href="#">All Collections</a></li>
                          <li><a href="#">Mother of Pearl</a></li>
                          <li><a href="#">Top 100 Designs</a></li>
                          <li><a href="#">Casetify Band</a></li>
                          <li><a href="#">Summer Vibes</a></li>
                          <li><a href="#">Macbook Sleeve</a></li>
                          <li><a href="#">Metaluxe</a></li>
                        </ul>
                      </li>
                      <!-- collection submenu close from here -->
                      <li>
                        <ul class="xskin-submenu">
                        <span class="menu-title">categories</span>
                          <li><a href="#">Hex</a></li>
                          <li><a href="#">Sprayground</a></li>
                          <li><a href="#">PKG</a></li>
                          <li><a href="#">Poler Stuff</a></li>
                          <li><a href="#">Agent 18</a></li>
                          <li><a href="#">Otter box</a></li>
                          <li><a href="#">Life proof</a></li>
                        </ul>
                      </li>
                      <li>
                        <ul class="xskin-submenu">
                        <span class="menu-title"></span>
                          <li><a href="#">Casemate</a></li>
                          <li><a href="#">UAG</a></li>
                          <li><a href="#">Evutec</a></li>
                          <li><a href="#">Jason Markk</a></li>
                        </ul>
                      </li>
                      <!-- categories submenu close from here -->

                      <li>
                        <ul class="xskin-submenu">
                        <span class="menu-title">featured artist</span>
                          <li><a href="#">Monika Strigel</a></li>
                          <li><a href="#">Girly Trend</a></li>
                          <li><a href="#">Girly Road</a></li>
                          <li><a href="#">Budi Kwan</a></li>
                          <li><a href="#">Eskayel</a></li>
                        </ul>
                      </li>
                      <!-- featured artist submenu close from here -->

                      <li>
                        <ul class="xskin-submenu">
                        <span class="menu-title">products</span>
                          <li><a href="#">Gift Card</a></li>
                          <li><a href="#">Selfie Stick</a></li>
                          <li><a href="#">Muku MacroWide</a></li>
                          <li><a href="#">Selfie Pack</a></li>
                        </ul>
                      </li>
                      <!-- products submenu close from here -->

                    </ul>
                  
              </li>
              <li><%= link_to"iPHONE6",iphone6_path,:class => active_class?(iphone6_path) %></li>
              <li><%= link_to"APPLE WATCH",apple_watch_path,:class => active_class?(apple_watch_path) %></li>
              <li class="xskin-search"><input type="submit" class="search_content" value="Send" /></li>
                </ul>
                </div>
                <!-- Xskin menu for destop close from here -->
                

                <nav class="tab-bar show-for-small-only">
                  <section class="left-small">
                    <a href="#" class="left-off-canvas-toggle menu-icon" aria-expanded="false"><span></span></a>
                    </section>
                      <section class="right tab-bar-section">
                        <h1 class="title">Menu</h1>
                      </section>
                      </nav>

                         </div>
                        <aside class="left-off-canvas-menu">
                          <ul class="off-canvas-list">
                            <li><label>Menu</label></li>
                            <li><a href="make-your-case.html">MAKE YOUR CASE</a></li>
                            <li><a href="#">STORE</a></li>
                            <li><a href="#">iPHONE6</a></li>
                            <li><a href="#">APPLE WATCH</a></li>
                          </ul>
                        </aside>

                        <!-- Search area for only mobile -->
                      <div class="xskin-mobile-search">
                          <div class="enter-keywords">
                          <input type="text" placeholder="Search Here" autofill="true" />
                          </div>
                          <div class="press-enter mobile-search">
                            <input type="submit" value="Send" />
                          </div>
                          <div class="xskin-cross-search-item">
                            <%= image_tag("close.png", class: "close-search") %>
                             </div>
                        </div>
                        <!-- Search area for only mobile close from here -->

                        </div>
                      <!-- row close from here -->
                        </header>
<%=render "layouts/currency" %>

app/views/layouts/_make_header.html.erb
<%= render"layouts/currency" %>       
        <header>
        <div class="large-12">
        <div class="large-6 left">
         <div class="back-to-xskin-website">
        <a href="<%= demo_path %>" title="Go back"><i class="fa fa-angle-left"></i> &nbsp;Go back to website</a>
      </div>
      </div>
       <div class="large-6 right">
        <div class="xskin-login text-right hide-for-small-only">
          <ul class="xskin-login-language">
          <li class="hide-for-small-only"><a data-reveal-id="xskin-currencyModal" href="#"><i class="fa fa-briefcase"></i>
          <% if cookies[:currency] %>
            <%= cookies[:currency] %>
          <% else %>
          CAD ($)
          <% end %>
          </a></li>
                 <% if user_signed_in? %>
      <li class="login last">
            <%=link_to"MyAccount",edit_user_registration_path %>
            </li>
            <li class="login last">
            <%=link_to"Logout",destroy_user_session_path,:method=>"delete"  %>
            </li>
            <li class="login last">
            <%=link_to"Cart","javascript:void(0);"  %>
            </li>
      <% else %>      
          <li class="login last">
          <%=link_to"LOGIN",new_user_session_path, :title=>"Login to start"  %>
          </li>
      <% end %> 
          </ul>
        </div>
        </div>
        </div>
        <div class="row">
        <div class="xskin-menu-with-logo make-your-case">
            <div class="large-12 medium-12 columns text-center">
            <div class="xskin-logo">
              <a href="#">
              <%=image_tag"Xskin-logo.png",:title=>"xskin" %>
              </a>
              </div>
              <div class="show-for-small-only mobile-search">
                <input type="submit" value="Send" />
              </div>
            </div>
            <!-- Xskin-logo close from here -->
                </div>
                        </div>
                          <!-- row close from here -->
                        </header>

app/views/layouts/_messages.html.erb
<%# Rails flash messages styled for Zurb Foundation %>
<% flash.each do |name, msg| %>
  <% if msg.is_a?(String) %>  
    <div data-alert class="row xskin-flash-message text-center alert-box radius <%= name.to_s == 'notice' ? 'success' : 'alert' %>">
      <%= content_tag :div, msg %>
      <a href="#" class="close">&times;</a>
    </div>
  <% end %>
<% end %>

app/views/layouts/_support_menu.html.erb
<ul class="xskin-user-list-categories xskin-privacy-policy">
  <li><%=link_to"Contact Us",contact_path,:class => active_class?(contact_path)%></li>
  <li>
  <%=link_to"Faq",faq_path,:class => active_class?(faq_path) %>
  </li>
  <li><a href="#">subcription</a></li>
  <li>
  <%= link_to"Privacy Policy",privacy_path,:class => active_class?(privacy_path) %>
  </li>
  <li><%=link_to"term & condition",terms_path,:class => active_class?(terms_path)%></li>
  <li><%= link_to"affiliate",affiliate_path ,:class => active_class?(affiliate_path)%></li>
  <li><%=link_to"Testimonial",testimonial_path ,:class => active_class?(testimonial_path) %></li>
  <li><%=link_to"Developer",developer_path,:class => active_class?(developer_path) %></li>
  <li><%=link_to"Careers",careers_path,:class => active_class?(careers_path) %></li>
  <li><%=link_to"spotting",spotting_path,:class => active_class?(spotting_path) %></li>
</ul>

app/views/layouts/_user_menu.html.erb
<ul class="xskin-user-list-categories">
	<li class="current1">
	<%=link_to"My profile", edit_user_registration_path,:class => active_class?(edit_user_registration_path)  %>           
	<li><%= link_to"My gallery", gallery_path,:class => active_class?(gallery_path) %>
	</li>
	<li><%= link_to"Track Order", track_path,:class => active_class?(track_path) %>
	</li>
	<li><%= link_to"invite friend", invite_path,:class => active_class?(invite_path) %>
	</li>
	<li><%= link_to"promotion", promotion_path,:class => active_class?(promotion_path) %>
	</li>
	<li><%=link_to"Log out",destroy_user_session_path,:method=>"delete"  %></li>
</ul>

app/views/page/home.html.erb
<section class="skin-content">
  <div class="row">
    <div class="xskin-content-section">
      <!-- sidebar start from here -->
        <div class="medium-3 left hide-for-small-only">
          <div class="sidebar">
            <div class="iphone-6">
            <%= image_tag "iPhone6-front.jpg" %>              
              <div class="masking smooth">
                <div class="xskin-add-to-cart">
                  <div class="add-to-cart">
                  <a href="#"><span class="smooth cart">
                  <%= image_tag "zoom.png" %>
                    </span></a>
                    <a href="#"><span class="smooth cart your-cart">
                    <%= image_tag "add-to-cart.png" %>
                    </span></a>
                  </div>
                </div>
              </div>
            </div>
            <!-- iPhone6 close from here -->
            <div class="iphone-6">
            <%= image_tag "iPhone6-back.jpg" %>
              <div class="masking smooth">
                <div class="xskin-add-to-cart">
                  <div class="add-to-cart">
                  <a href="#"><span class="smooth cart">
                    <%= image_tag "zoom.png" %>
                    </span></a>
                    <a href="#"><span class="smooth cart your-cart">
                    <%= image_tag "add-to-cart.png" %>
                    </span></a>
                  </div>
                </div>
              </div>
            </div>
            <!-- iPhone6 close from here -->
          </div>
        </div>
        <!-- sidebar close from here -->


        <!-- slider start from here -->
        <div class="medium-6 columns">

        <div class="slide-start">
          <div class="xskin-slider">
            <div class="xskin-slide">
              <%=image_tag"iphone-background.jpg",:class=>"xskin-slide-back-img" %>
            </div>

            <div class="xskin-slide-caption">
              <div class="caption">
                <div class="make-your-own-skin">
                  <div class="slide-cap">
                    <h2>make your own</h2>
                    <h1>skin</h1>
                    <a href="#" class="button">Learn More</a>
                  </div>
                </div>
              </div>
            </div>
            <!-- slide caption close from here -->
          </div>

          <div class="xskin-slider">
            <div class="xskin-slide">
              <%=image_tag"iphone-background-1.jpg",:class=>"xskin-slide-back-img" %>
            </div>

            <div class="xskin-slide-caption">
              <div class="caption">
                <div class="make-your-own-skin">
                  <div class="slide-cap">
                    <h2>make your own</h2>
                    <h1>skin</h1>
                    <a href="#" class="button">Learn More</a>
                  </div>
                </div>
              </div>
            </div>
            <!-- slide caption close from here -->
          </div>
          <div class="xskin-slider">
            <div class="xskin-slide">
              <%=image_tag"iphone-background-2.jpg",:class=>"xskin-slide-back-img" %>
            </div>

            <div class="xskin-slide-caption">
              <div class="caption">
                <div class="make-your-own-skin">
                  <div class="slide-cap">
                    <h2>make your own</h2>
                    <h1>skin</h1>
                    <a href="#" class="button">Learn More</a>
                  </div>
                </div>
              </div>
            </div>
            <!-- slide caption close from here -->
          </div>
          <div class="xskin-slider">
            <div class="xskin-slide">
              <%=image_tag"iphone-background-3.jpg",:class=>"xskin-slide-back-img" %>
            </div>

            <div class="xskin-slide-caption">
              <div class="caption">
                <div class="make-your-own-skin">
                  <div class="slide-cap">
                    <h2>make your own</h2>
                    <h1>skin</h1>
                    <a href="#" class="button">Learn More</a>
                  </div>
                </div>
              </div>
            </div>
            <!-- slide caption close from here -->
          </div>

          </div>

        </div>
        <!-- slider close from here -->


        <div class="medium-3 left hide-for-small-only">
          <div class="sidebar">
            <div class="iphone-6">
              <%=image_tag"girl-using-iphone.jpg" %>
              <div class="xskin-top-design">
              <div class="caption">
                <div class="make-your-own-skin">
                  <div class="slide-cap">
                    <h3>top 100<br><span>Design</span></h3>
                    <%= link_to"See More", top_design_path,:class=>"button" %>
                  </div>
                </div>
              </div>
              </div>
              <!-- top design caption close from here -->

            </div>
            <div class="iphone-6">
              <%=image_tag"mans-using-iphone.jpg" %>
              <div class="xskin-top-design">
              <div class="caption">
                <div class="make-your-own-skin">
                  <div class="slide-cap">
                  <h5>Give your friend</h5>
                  <h3>get &dollar;10</h3>
                  <%= link_to"See More", invite_path,:class=>"button" %>
                  </div>
                </div>
              </div>
              </div>
              <!-- top design caption close from here -->
            </div>
          </div>
        </div>
        </div>
      <!-- design only for mobile -->
      <div class="small-12 show-for-small-only">
          <div class="xskin-slider">
            <div class="xskin-slide">
              <%=image_tag "iphone-background.jpg" %>
            </div>
            <div class="xskin-slide-caption">
              <div class="caption">
                <div class="make-your-own-skin">
                  <div class="slide-cap">
                    <h2>make your own</h2>
                    <h1>skin</h1>
                    <a class="button" href="#">Learn More</a>
                  </div>
                </div>
              </div>
            </div>
            <!-- slide caption close from here -->
          </div>
        </div>
        <div class="small-12 left show-for-small-only">
          <div class="sidebar">
            <div class="iphone-6">
              <%=image_tag"girl-using-iphone.jpg" %>
              <div class="xskin-top-design">
              <div class="caption">
                <div class="make-your-own-skin">
                  <div class="slide-cap">
                    <h3>top 100<br><span>Design</span></h3>
                    <a href="#" class="button">see more</a>
                  </div>
                </div>
              </div>
              </div>
              <!-- top design caption close from here -->
            </div>
            <div class="iphone-6">
              <%=image_tag"mans-using-iphone.jpg" %>

              <div class="xskin-top-design">
              <div class="caption">
                <div class="make-your-own-skin">
                  <div class="slide-cap">
                  <h5>Give your friend</h5>
                    <h3>get &dollar;10</h3>
                    <a href="#" class="button">see more</a>
                  </div>
                </div>
              </div>
              </div>
              <!-- top design caption close from here -->
            </div>
          </div>
        </div>
        <div class="small-12 left show-for-small-only">
          <div class="sidebar">
            <div class="iphone-6 mobile-view">
              <%=image_tag"iPhone6-front.jpg" %>
              <div class="masking smooth">
                <div class="xskin-add-to-cart">
                  <div class="add-to-cart">
                  <a href="#"><span class="smooth cart">
                    <%=image_tag"zoom.png" %>
                    </span></a>
                    <a href="#"><span class="smooth cart your-cart">
                    <%=image_tag"add-to-cart.png" %>
                    </span></a>
                  </div>
                </div>
              </div>
            </div>
            <!-- iPhone6 close from here -->
            <div class="iphone-6 mobile-view">
              <%=image_tag"iPhone6-back.jpg" %>
              <div class="masking smooth">
                <div class="xskin-add-to-cart">
                  <div class="add-to-cart">
                  <a href="#"><span class="smooth cart">
                    <%=image_tag "zoom.png" %>
                    </span></a>
                    <a href="#"><span class="smooth cart your-cart">
                    <%=image_tag"add-to-cart.png" %>
                    </span></a>
                  </div>
                </div>
              </div>
            </div>
            <!-- iPhone6 close from here -->
          </div>
        </div>
        </div>
</section>